<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2015/6/23
 * Time: 13:31
 */

namespace app\controllers;


use app\models\TestModel;
use app\modules\admin\models\User;
use yii\data\ActiveDataProvider;
use yii\filters\auth\HttpBasicAuth;
use yii\rest\ActiveController;
use yii\rest\Serializer;
use yii\web\HtmlResponseFormatter;
use yii\web\Response;

class UserController extends ActiveController{

    public $modelClass = 'app\models\TestModel';

    public function init()
    {

        parent::init();
        \Yii::$app->user->enableSession = false;
    }


    /**
     * 定义actions
     * @return array
     */
    public function actions()
    {

        $actions = parent::actions();

        //unset($actions['create']) ;


        //设置index操作的dataProvider
        $actions['index']['prepareDataProvider'] = [$this, 'prepareDataProvider'];



        return $actions;
    }

    /**
     * 定义dataprovider
     * @return ActiveDataProvider
     */
    public function prepareDataProvider($obj)
    {

        $dataProvider = new ActiveDataProvider([
            'query' => TestModel::find()->where(['>','ac_id', 14412])
        ]);
        return $dataProvider;
    }

    /**
     * 定义自己的action
     * @param $id
     * @return null|static
     */
    public function actionMyview($id)
    {

        p($_REQUEST);
        p($_POST);
        p($_GET);

        return TestModel::findOne($id);
    }


    public function actionCreate($id)
    {
        exit;
        p($_REQUEST);
        p($_POST);
        p($_GET);
        return parent::createAction($id); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();

        /*//设置权限认证
        $behaviors['authenticator'] = [
            'class' => HttpBasicAuth::className()
        ];*/

        $behaviors['contentNegotiator']['formats']['text/html'] = Response::FORMAT_JSON;

        return $behaviors;
    }

    public function checkAccess($action, $model = null, $params = [])
    {


        //parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
    }

}