<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2015/7/31
 * Time: 11:10
 */

namespace app\modules\shop\controllers;


use yii\web\Controller;

class BaseController extends Controller{


    public $layout  = 'main';

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }


}