<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2015/6/24
 * Time: 14:46
 */

namespace app\widgets;


use yii\base\Widget;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\web\View;

class AjaxFileUploadWidget extends Widget{

    public $objClass='';


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }

    public function run()
    {

        $this->_ajaxUpload($this->objClass);

    }

    /**
     * * Eg.: <ViewTag:upload action="/upload.php" filetype="*.jpg;*.png;*.gif" filetypedesc="图片(.jpg,.png,.gif)" width="120" height="30" multi="false" for="" />
     * @param $attr
     * @return string|void
     */
    public function _ajaxUpload($objClass)
    {


        \Yii::$app->view->on(View::EVENT_END_PAGE, function () {

            echo Html::jsFile("@web/js/ext/ajaxFileUpload.js");

            $objClass = $this->objClass;
            $str = <<<STD

            <script type="text/javascript">
            //data {id:id, url:url, otherData:otherData}
            function ajaxFileUpload(data)
            {

                var id = data.id;
                var url = data.url;
                var otherData = data.otherData?data.otherData:{};
                $.ajaxFileUpload ({
                    url: url,
                    secureuri:false,
                    fileElementId:id,
                    dataType: 'json',
                    data:{name:'logan', id:otherData},
                    success: function (data)
                    {

                        var file_name = data.data.file_name;
                        var objClass = $('#'+id).attr('point-class');
                        var showImageId = $('#'+id).attr('point-img');

                        $('.'+objClass).val(file_name);
                        $('#'+showImageId).attr('src', data.data.img_src).show();

                        return false;

                    },
                    error: function (data, status, e)
                    {
                       alert(e);
                    }
                });

                return false;
            }

            </script>
STD;

            $strBindEvent = <<<STD

            <script type="text/javascript">

            function onFileChange(obj){

                var id = obj.attr('id');
                var url = obj.attr('data-url');
                var otherData = {name:id}
                var data = {id:id, url:url, otherData:otherData};

                ajaxFileUpload(data, otherData);
            }

            function bindUploadAction() {

               var objClass = '{$objClass}';

                $(document).on("change",objClass,function(){//修改成这样的写法

                    onFileChange($(this))

                });

            }


            $(function(){

                bindUploadAction();
            })

            </script>
STD;
            echo $str.$strBindEvent;
        });

    }




}