<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2015/6/24
 * Time: 14:46
 */

namespace app\widgets;


use yii\base\Widget;
use yii\bootstrap\Modal;
use yii\web\View;

class ModalWidget extends Widget{

    const MODAL_TYPE_IFRAME = 'iframe';
    const MODAL_ID_IFRAME = 'iframeModal';

    public $modalType = 'iframe';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }

    public function run()
    {
        if($this->modalType == self::MODAL_TYPE_IFRAME)
            $this->run_iframe();
    }


    /**
     * iframe modal 框架模态弹出窗
     */
    private function run_iframe()
    {

        \Yii::$app->view->on(View::EVENT_END_BODY, function () {


            Modal::begin([
                'id' => 'iframeModal',
                'header' => '<h4 class="modal-title"> Header </h4>',
                'footer' => '<a href="#" class="btn btn-primary" data-dismiss="modal">Close</a>',
                'size' => Modal::SIZE_LARGE
            ]);

            echo '<iframe ></iframe>';

            Modal::end();
        });



        $this->ifram_jscode();

    }

    /**
     * 输出iframe modal 的js代码, 控制iframe的url地址跳转及iframe的宽高大小
     */
    private function ifram_jscode()
    {

        \Yii::$app->view->on(View::EVENT_END_PAGE, function () {

            $jsString = <<<STR

            <script type="text/javascript">
                $(document).on('click', '.btn_show_modal', function(){

                    id = '#iframeModal';

                    $(id).find('iframe')
                         .attr('src',$(this).val())
                         .css({'width':'100%','border':'none','height':'500px'});

                    $(id).find('.modal-title').html($(this).attr('title'));

                });
            </script>
STR;
            echo $jsString;
        });
    }


}