<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2015/6/24
 * Time: 14:46
 */

namespace app\widgets;


use yii\base\Widget;
use yii\bootstrap\Modal;
use yii\web\View;

class Shop_config_editWidget extends Widget{



    public $group = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (!is_array($this->group) || count($this->group) < 1) {
            return false;
        }
    }

    public function run()
    {

        $_lang = \Yii::$app->params['lang'];
        return $this->render('Shop_config_editWidget',
                [
                    'group' => $this->group,
                    'lang'  => $_lang,
                    'countries' => get_regions(),
                    'provinces' => get_regions(1,1),
                    'cities' => get_regions(2,2),
                ]
            );
    }

}