<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2015/7/30
 * Time: 17:08
 */
namespace app\modules\shop;
use yii\base\Module;

class ShopModule extends Module{

    public $controllerNamespace = 'app\modules\shop\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}